### ISSUE TITLE
Not able to login when NODE_ENV=production

### ISSUE THREAD

**Issue by robincsamuel** [SoftwareBrothers/admin-bro-expressjs#5]
Authentication works fine on the development environment. But if I set the NODE_ENV to production, it won't.

I see the server is still responding with 200 OK, but it's getting redirected to the login page.

Also, I noticed a warning,
```
express-session deprecated undefined resave option;
express-session deprecated undefined saveUninitialized option
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
```
It would be nice if the default cookie parser and session is configured only no predefined router is passed. Or at least an option to skip that, so that I can pass a predefined router with session configuration. I'm not using the `buildRouter` since I want the authentication methods.

**Comment by robincsamuel** [comment]
Just realized that my middleware was looking for a secure cookie.

Sorry to spam! Thanks!

**Comment by mikypilota** [comment]
Hi, would you mind being a bit more specific about what the issue was and how did you solve it?

**Comment by robincsamuel** [comment]
> Hi, would you mind being a bit more specific about what the issue was and how did you solve it?

It was my express session configuration. I had secure cookie enabled, like the sample config below, but my application wasn't SSL enabled.
 
```
app.use(express.session({
  cookie: {
    secure: true
  }            
}));
```
