### ISSUE TITLE
express-session deprecated undefined resave option & undefined saveUninitialized option.

### ISSUE THREAD

**Issue by rafagarciac** [SoftwareBrothers/admin-bro-expressjs#8]
When I set up [Role-Based Access Control](https://softwarebrothers.github.io/admin-bro-dev/tutorial-08-rbac.html) in my Express API got the next warnings:
---
**Warnings** 
```
express-session deprecated undefined resave option; provide resave option node_modules/admin-bro-expressjs/plugin.js:131:14
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option node_modules/admin-bro-expressjs/plugin.js:131:14
```
---
**Versions**
```
"admin-bro": "^1.3.5",
"admin-bro-expressjs": "^0.2.0",
"admin-bro-sequelizejs": "^0.2.6",
"admin-bro-theme-dark": "^1.0.0",
"cookie-parser": "~1.4.4",
"express": "~4.16.1",
"express-session": "^1.17.0",
```

**Comment by wojtek-krysiak** [comment]
https://softwarebrothers.github.io/admin-bro-dev/module-admin-bro-expressjs.html#.buildAuthenticatedRouter has sessionOptions - you can pass `resave` and `saveUninitialized` there.

**Comment by Swarag-N** [comment]
```
const Admin ={
	email : process.env.EMAIL_OF_ADMIN   || 'example@c4p.com',
	password : process.env.PASSWORD_OF_ADMIN || 'coding'
};


AdminBroExpressjs.buildAuthenticatedRouter(adminBro,{
	authenticate:async(email, password)=>{
		if (email === Admin.email && password === Admin.password) {
			return Admin
		}
    return null
  },
  cookieName: process.env.COOKIE_ADMIN_NAME || 'C-4-P',
  cookiePassword: process.env.COOKIE_ADMIN_PASSWORD || 'admin-bro',
  },
  adminRouter,
  {
      resave:true,
      saveUninitialized: true
  }
);
````

I have passed the arguments like these but i still get the same errors

```
express-session deprecated undefined resave option; provide resave option node_modules\admin-bro-expressjs\plugin.js:131:14
express-session deprecated undefined saveUninitialized option; provide saveUninitialized option node_modules\admin-bro-expressjs\plugin.js:131:14
AdminBro: bundle ready
```

Thanks in Advance

**Comment by naterexw** [comment]
> ```
> const Admin ={
> 	email : process.env.EMAIL_OF_ADMIN   || 'example@c4p.com',
> 	password : process.env.PASSWORD_OF_ADMIN || 'coding'
> };
> 
> 
> AdminBroExpressjs.buildAuthenticatedRouter(adminBro,{
> 	authenticate:async(email, password)=>{
> 		if (email === Admin.email && password === Admin.password) {
> 			return Admin
> 		}
>     return null
>   },
>   cookieName: process.env.COOKIE_ADMIN_NAME || 'C-4-P',
>   cookiePassword: process.env.COOKIE_ADMIN_PASSWORD || 'admin-bro',
>   },
>   adminRouter,
>   {
>       resave:true,
>       saveUninitialized: true
>   }
> );
> ```
> 
> I have passed the arguments like these but i still get the same errors
> 
> ```
> express-session deprecated undefined resave option; provide resave option node_modules\admin-bro-expressjs\plugin.js:131:14
> express-session deprecated undefined saveUninitialized option; provide saveUninitialized option node_modules\admin-bro-expressjs\plugin.js:131:14
> AdminBro: bundle ready
> ```
> 
> Thanks in Advance

You set it up wrong.  Check here for correct way:
https://github.com/JSCasts-episodes/ep18-admin-bro-startup-part3

```
const router = buildAuthenticatedRouter(admin, {
  cookieName: 'admin-bro',
  cookiePassword: 'superlongandcomplicatedname',
  authenticate: async (email, password) => {
    const company = await Company.findOne({ email });

    if (company && await argon2.verify(company.encryptedPassword, password)) {
      return company.toJSON();
    }
    return null;
  },
}, null, {
  resave: false,
  saveUninitialized: true,
});
```
